services:
  rate-api:
    image: tripladev/rate-api
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  interview-dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
    environment:
      - RATE_API_URL=http://rate-api:8080
      - REDIS_URL=redis://redis:6379
      - ADMIN_TOKEN=ce2c7c1df165336a21e04cd917875f0f
    depends_on:
      - rate-api
      - redis

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/rails
    environment:
      - REDIS_URL=redis://redis:6379
      - RATE_API_URL=http://rate-api:8080
    depends_on:
      - redis
